version: 2
jobs:
  build:
    working_directory: ~/jpa-metamodels-with-maven-example
    docker:
      - image: circleci/openjdk:11.0.4-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: jpa-metamodels-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jpa-metamodels-with-maven-example-{{ checksum "pom.xml" }}
      - run: mvn -Phibernate-dependency clean package
      - run: mvn -Phibernate-processor clean package
      - run: mvn -Peclipselink-dependency clean package
      - run: mvn -Peclipselink-processor clean package
      - run: mvn -Popenjpa-dependency clean package
      - run: mvn -Popenjpa-processor clean package
      - run: mvn -Pdatanucleus-dependency clean package
      - run: mvn -Pdatanucleus-processor clean package

#      - store_test_results:
#          path: target/surefire-reports
#      - store_artifacts:
#          path: target/bit-io/
